server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-resume-matcher
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_resume_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  elasticsearch:
    uris: http://localhost:9200
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

ai-service:
  base-url: ${AI_SERVICE_URL:http://localhost:8001}

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.airesumemaker: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
