server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-resume-matcher
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:ai_resume_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Custom configuration for AI service
aiservice:
  base-url: ${AI_SERVICE_URL:http://fastapi-ai-service:8001}

# Custom configuration for JWT
security:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: 86400000

logging:
  level:
    '[com.airesumemaker]': INFO
    '[org.springframework.security]': INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics